### ISSUE TITLE
A blueprint's name collision occurred between

### ISSUE THREAD

**Issue by yim0823** [teamclairvoyant/airflow-rest-api-plugin#15]
i configured plugin according to your README.md.
when i restarted web server, the following error occurs :
AssertionError: A blueprint's name collision occurred between <flask.blueprints.Blueprint object at 0x7f6188e873d0> and <flask.blueprints.Blueprint object at 0x7f6188e87310>.  Both share the same name "rest_api".  Blueprints that are created on the fly need unique names.

The selected version is v1.0.3. 
Airflow version is 1.8.0.

**Comment by lavusridhar** [comment]
Can you check your plugins directory to see if you maybe have 2 copies of the plugin, maybe in some nested form? For example,
```
~/airflow/plugins/rest_api_plugin.py
~/airflow/plugins/plugins/rest_api_plugin.py
```

**Comment by yim0823** [comment]
Wow. Thank you so much. You were right.

my directorys:
~/airflow/plugins/rest_api_plugin.py
~/airflow/plugins/rest_api_plugin.pyc
~/airflow/plugins/templates
~/airflow/plugins/airflow-rest-api-plugin-1.0.3

The last directory was a problem. Deleted the last directory and resolved.

**Comment by rssanders3** [comment]
Thanks for helping to debug @lavusridhar. 

@yim0823 I would just like to follow up, was there an issue with the deployment process specified in the README that we need to fix?
