### ISSUE TITLE
Rest api run id is coming as manual

### ISSUE THREAD

**Issue by kranthikiran** [teamclairvoyant/airflow-rest-api-plugin#19]
After I upgrade rest api version . Present run id is showing manual even though if we launch thru rest api . Could you please help me on this ?. I am using below versions.

Airflow Version: 1.7.1.3
Rest API Plugin Version: 1.0.3

Thanks

**Comment by aravindboppana** [comment]
Hello Kranthikiran,
You will get run id as "manual"  for the dags that you trigger from the command line.If you schedule them you will get the run id as scheduled.
The REST API triggers command line commands in the background. So, you will get the dag triggered as manual.
