### ISSUE TITLE
trigger_dag should be instead of trigger_dag Operator

### ISSUE THREAD

**Issue by liuliqiang** [teamclairvoyant/airflow-rest-api-plugin#2]
as airflow docs [Airflow Api Document](https://airflow.incubator.apache.org/code.html) show, there is an Operator named `TriggerDagRunOperator` can trigger a dag , it can be used in this plugin and better than cmdline way.

**Comment by rssanders3** [comment]
Triggering a dag in a similar fashion to the other CLI processes was the first attempt to get REST services working. True there are more code friendly options which involves using similar code to what is being done  in the TriggerDagRunOperator. The disadvantage of using this type of code based trigger though is now, if the objects or APIs change between versions then we'd have to maintain that. Where as if we were to just trigger the command line interface, all that is handled by the CLI. Plus we'd also loose some visibility into execution of the command that can be returned via the REST service.

I'll look into what it would take to apply this change and see if its backwards compatible in future versions of Airflow.

**Comment by liuliqiang** [comment]
Got it , it my opinion and i believe using subprocess in each REST API is not a good idea. As a rest api for whole airflow, we should more dependent on airflow's origin feature and upgrade with airflow's change. Anyway, thanks for your reply and let me realize it's still an alive project ^_^
