### ISSUE TITLE
Compatibility with RBAC

### ISSUE THREAD

**Issue by rushtokunal** [teamclairvoyant/airflow-rest-api-plugin#22]
Hi,

when i star using the RBAC functionality with v2.0, the admin link doesn't exist anymore, is there a way i can still use the plugin with the new links starting with /home ?

**Comment by rssanders3** [comment]
Hello rushtokunal, I have not tested this with the new RBAC controls in the pre-release version of v2.0 of Airflow. I'm not sure what changes were made to enable RBAC but the plugin itself doesn't leverage any APIs for it since they were not available during the inception of this project. So we'd have to check this out.

**Comment by oyamin** [comment]
Yeah, Support to RBAC would be nice. I tried updating the home url from admin/rest_api to home/rest_api without any luck. 
They added RBAC from version 1.10.

**Comment by syedatifakhtar** [comment]
So i have a fix* for getting this to work with RBAC, im not too good with Python but since we needed this i got around to making some modifications on my own.What would it take for this plugin to fully support Airflow v1.10+ .I can put some effort into getting this to work if provided direction.

**Comment by bryan3189** [comment]
@syedatifakhtar  How did you get around this issue?
@rssanders3 Any ETA on when a fix for this will be available?

Thanks!

**Comment by bryan3189** [comment]
Tried @atiftw solution with no luck. I can view the API UI but get 404 for all the API endpoints

**Comment by bryan3189** [comment]
Update: Was able to get around this by tweaking @atiftw solution. Let me know if anybody needs the new plugin file.

**Comment by sudhakar-nallam** [comment]
RBAC support was enabled in the latest release v1.0.8
