### ISSUE TITLE
unable t trigger a dag

### ISSUE THREAD

**Issue by aashishjoshi-ekryp** [teamclairvoyant/airflow-rest-api-plugin#24]
I am getting below error in response when i am triggering a dag via API:

"stderr": "/home/miniconda/lib/python2.7/site-packages/airflow/models.py:2160: PendingDeprecationWarning: Invalid arguments were passed to DataProcPySparkOperator. Support for passing such arguments will be dropped in Airflow 2.0. Invalid arguments were:\n*args: ()\n**kwargs: {'region': 'us-west1'}\n  category=PendingDeprecationWarning\n"

Below is GET request i am sending
http://XX.XX.XX.XX:8080/admin/rest_api/api?api=trigger_dag&dag_id=MLPipeline&run_id=dummyUser1_2018-06-07 13:21:49&conf=%7B%22customerName%22%3A%20%22dummyUser1%22%7D

What I am missing here?

**Comment by rssanders3** [comment]
Can you confirm what version of Airflow you're running and which version of the plugin?

**Comment by rssanders3** [comment]
Hello @aashishjoshi-ekryp, 

It looks like this is actually working fine and the Error you're seeing is only a Depreciation warning. Can you confirm:
- The exit code
- If the dag_run is actually created or not
- What you get from the stdout

**Comment by rssanders3** [comment]
Closing since we haven't heard back with any more details. Please provide details and we'll look into this again.
