### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by ajanoni** [teamclairvoyant/airflow-rest-api-plugin#27]
Hi. I am trying to install the plugin following instructions here but it is not working.
I am using this airflow version: 2.0.0dev0+incubating

**Comment by ajanoni** [comment]
Realized that is due to RBAC been enabled.
Just disabled it and it started working

**Comment by rsubra13** [comment]
Is there any plans for this plugin to work for the Airflow 1.10 and further versions with RBAC?

**Comment by rssanders3** [comment]
Thanks for confirming you've resolved this issue @ajanoni.

We'll hopefully be able to work on checking compatibility with Airflow 1.10 in the coming months.
