### ISSUE TITLE
deploy dag when using  CeleryExecutor 

### ISSUE THREAD

**Issue by ZhitongLei** [teamclairvoyant/airflow-rest-api-plugin#28]
Hi,
When using CeleryExecutor, we will start works on different machines,  but it seems that the deploy_dag api only support deploying file to a single machine, so I must start airflow webserver on every machine.

Is there  a better way to deploy dag when using  CeleryExecutor?

**Comment by rssanders3** [comment]
Hello @ZhitongLei,

The deploy dag operation was built more for a single node deployment of Airflow. How we've done this though, and how you could also do this if you have a cluster setup, is mount a shared folder to the directories where the DAGs are distributed. That way if you deploy your DAG into one of those directories it automatically gets distributed to the other machines.
