### ISSUE TITLE
airflow variables set

### ISSUE THREAD

**Issue by eddielisc** [teamclairvoyant/airflow-rest-api-plugin#3]
how to call in api if i want to do the following

`airflow varaibles set key value`

i always get error when i call it in api

```
{ "airflow_cmd": "airflow variables --set shortCircuitIsRun True", "arguments": { "set": "shortCircuitIsRun True" }, "call_time": "Tue, 21 Mar 2017 17:10:03 GMT", "output": { "stderr": "usage: airflow variables [-h] [-s KEY VAL] [-g KEY] [-j] [-d VAL]\n [-i FILEPATH] [-e FILEPATH] [-x KEY]\nairflow variables: error: argument -s/--set: expected 2 argument(s)\n", "stdout": "[2017-03-22 10:02:52,058] {__init__.py:57} INFO - Using executor CeleryExecutor\n" }, "response_time": "Wed, 22 Mar 2017 10:02:54 GMT", "status": "OK" }
```

**Comment by rssanders3** [comment]
Hello eddislic,

Thanks a lot for bringing this to my attention. I noticed this very recently issue as I was refactoring the code in the **v1.0.0-branch** branch. This does appear to be a minor bug with the code. If you're working with whats currently in the master branch (https://github.com/teamclairvoyant/airflow-rest-api-plugin/tree/be685e3337bec168f994fadbdde85a6d1d3f8e40) then the fix that you can do to get this to work right away is this:

on line #140, you can update the line 'command_split.extend(["--set", set])' to be 'command_split.extend(["--set"] + set.split(" "))'. 

I have already created a release from the current master branch as release **v0.0.1**. When I get some time, I will create a new release with this fix on it called **v0.0.2** and I will let you know when this is done.

As I mentioned before, I currently have a new branch going **v1.0.0-branch** which should make things much easier to manage and provide some new features. The fix has already been applied to this branch if you wish to pull from there. This will eventually become the v1.0.0 release.

**Comment by eddielisc** [comment]
good to know. Thanks for your reply. 
happy coding

**Comment by rssanders3** [comment]
Made the fix, tested it, merged it back into the master branch and create a new release from it: https://github.com/teamclairvoyant/airflow-rest-api-plugin/releases/tag/v0.0.2

Let me know if you continue to have the same issues.

**Comment by arpangupta** [comment]
Hi @rssanders3,

I am using `apache-airflow==1.9.0` and I have tried both `v1.0.4` and `v1.0.4-branch` versions of the airflow-rest-api-plugin. I am still getting the same error when I call the set API for variables like this:
`/admin/rest_api/api?api=variables&set=my_var var_value`

Stderr error that I get is this:
`"usage: airflow variables [-h] [-s KEY VAL] [-g KEY] [-j] [-d VAL]\n                         [-i FILEPATH] [-e FILEPATH] [-x KEY]\nairflow variables: error: argument -s/--set: expected 2 argument(s)\n"`

I understand from the conversation above that it was already fixed in V0.0.2. Am I missing something here?

Cheers,
Arpan Gupta

**Comment by rssanders3** [comment]
Hello @arpangupta,

Sorry this is not clear in the documentation, but you should include a '+' between the key and value to account for the space it needs to pass in to the airflow cli command.

So it should be `/admin/rest_api/api?api=variables&set=my_var+var_value`

Thanks!
Robert

**Comment by arpangupta** [comment]
Hi Robert,

I had already tried (and retried on seeing your reply) adding a '+' or '%20' but it still didn't work for me.
Are you sure you tried it on `v1.0.4` of the airflow rest plugin?

Thanks,
Arpan

**Comment by rssanders3** [comment]
Yes I'm using v1.0.4 in the testing i did to confirm. Can you send the exact key and value you're using?

Thanks,
Robert

**Comment by arpangupta** [comment]
Hi Robert,

Sorry for the delay in response.
I am using exactly the same key and value i.e. my_var and var_value. So, my URL(local) looks like this:
`http://localhost:8080/admin/rest_api/api?api=variables&set=my_var+var_value`
Response:
`{
    "airflow_cmd": "airflow variables --set my_var var_value",
    "arguments": {
        "api": "variables",
        "set": "my_var var_value"
    },
    "call_time": "Thu, 19 Apr 2018 12:24:08 GMT",
    "http_response_code": 200,
    "output": {
        "stderr": "usage: airflow variables [-h] [-s KEY VAL] [-g KEY] [-j] [-d VAL]\n                         [-i FILEPATH] [-e FILEPATH] [-x KEY]\nairflow variables: error: argument -s/--set: expected 2 argument(s)\n",
        "stdin": "",
        "stdout": ""
    },
    "post_arguments": {},
    "response_time": "Thu, 19 Apr 2018 12:25:36 GMT",
    "status": "OK"
}`

Also, the version is 1.0.4
`http://localhost:8080/admin/rest_api/api?api=rest_api_plugin_version`
Response:
`{
    "arguments": {
        "api": "rest_api_plugin_version"
    },
    "call_time": "Thu, 19 Apr 2018 12:24:08 GMT",
    "http_response_code": 200,
    "output": "1.0.4",
    "post_arguments": {},
    "response_time": "Thu, 19 Apr 2018 12:24:42 GMT",
    "status": "OK"
}`

Thanks,
Arpan

**Comment by ahsanshah** [comment]
Same issue here.  "argument -s/--set: expected 2 argument(s)\n""  Any idea what version resolves this issue?

**Comment by nbhoj** [comment]
any updates on this?
