### ISSUE TITLE
Warnning： airflow webserver

### ISSUE THREAD

**Issue by zhengyscn** [teamclairvoyant/airflow-rest-api-plugin#30]
env:
python3.7
centos7.3
apache-airflow             1.10.2 
mysql 5.7

plugins:
# grep plugins airflow/airflow.cfg \
plugins_folder = /root/airflow/plugins

# ll /root/airflow/plugins/
总用量 60
drwxr-xr-x 2 root root  4096 3月   2 10:59 __pycache__
-rw-r--r-- 1 root root 52422 1月  11 03:44 rest_api_plugin.py
drwxr-xr-x 3 root root  4096 1月  11 03:44 templates

Start warnning
[2019-03-02 12:28:08,558] {configuration.py:255} WARNING - section/key [rest_api_plugin/rest_api_plugin_http_token_header_name] not found in config
[2019-03-02 12:28:08,558] {configuration.py:255} WARNING - section/key [rest_api_plugin/rest_api_plugin_expected_http_token] not found in config

**Comment by sudhakar-nallam** [comment]
@zhengyscn Is this warning causing any impact on the Plugin functionality for you.

**Comment by sudhakar-nallam** [comment]
@zhengyscn When a key is not found in the configuration file Airflow throws this warning message. To suppress these warning messages please add the following entries in the Airflow configuration file under the `rest_api_plugin` section.

    [rest_api_plugin]
    # HTTP Header Name to be used for authenticating REST calls for the REST API Plugin
    rest_api_plugin_http_token_header_name = 

    # HTTP Token  to be used for authenticating REST calls for the REST API Plugin
    rest_api_plugin_expected_http_token =
