### ISSUE TITLE
User based Authentication

### ISSUE THREAD

**Issue by dkurtarkar** [teamclairvoyant/airflow-rest-api-plugin#35]
Airflow UI has user based DAG (view/execution).
Does the REST API PLUGIN support this, as I see only simple token-based authentication is being supported and it has not user-related info.

We want only DAG-owners to be able to execute the tasks within the DAGs via REST API plugin.

**Comment by chenglin** [comment]
We want use Airflow with enable "authenticate = True" and it seems that the REST API PLUGIN does not support user/password based authentication.

**Comment by rssanders3** [comment]
A similar question was brought up: https://github.com/teamclairvoyant/airflow-rest-api-plugin/issues/22. Closing duplicate.
