### ISSUE TITLE
Is there a way to pass parameters in headers while calling the trigger_dag API  ?

### ISSUE THREAD

**Issue by abhishek-kumar0409** [teamclairvoyant/airflow-rest-api-plugin#43]

**Comment by rssanders3** [comment]
Hello @abhishek-kumar0409, this capability does not currently exist. The only way to pass in arguments is through the POST body or GET parameters in the URL.

**Comment by abhishek-kumar0409** [comment]
Thanks @rssanders3 for your reply. Any plans of adding the support in future ?

**Comment by rssanders3** [comment]
We currently don't have any plans to support this as you can already pass arguments in through GET arguments or the POST body which are apart of standard REST API practices. For what reason are you looking to pass in arguments through headers?

**Comment by abhishek-kumar0409** [comment]
Hi @rssanders3 ,
There is one use case that I was trying to work on. I wanted to pass a transaction-id or request-id in the headers and append this id to the log-formatter in the workflow. So, I wanted the request-id (passed from the header) to be printed in the every line of the log along with the TestRunID of workflow. 

The idea of using request-id is to stitch the workflow log with the northbound system that is responsible for triggering the workflow. You can think of a usecase, where an API request is initiated from a backend microservice, a request-id is generated for this API request,  this request-id is passed to the airflow and captured in the log files. So, this can be useful for  log monitoring and analysis to know what happened to the airflow workflow operation for that given request-id.  I'm not sure whether it's achievable using airflow or not but wanted to git a try. Could you please suggest ?

**Comment by rssanders3** [comment]
Hello @abhishek-kumar0409, I'm not sure you can change the log format to include this in every single log entry. But my question is also, why do you need the transaction/request id added to each line? What I think you could do is pass the transaction/request id in as a config to the trigger_dag function and then you can access this configuration from inside the context:

From PythonOperator:
request_id = context['dag_run'].conf.get("request_id")

**Comment by abhishek-kumar0409** [comment]
Hi Robert,
 We have been using the approach only for the time being. I wanted to know
if there is a way to achieve passing some custom header parameters. Looks
like it's not supported. I will close the issue.

Thanks ,
Abhishek

**Comment by rssanders3** [comment]
OK, thanks @abhishek-kumar0409 for the inquiry. Closing the issue.
