### ISSUE TITLE
403 Forbidden-You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

### ISSUE THREAD

**Issue by wenchangming211** [teamclairvoyant/airflow-rest-api-plugin#45]
hello, I encountered such a problem in Version: 1.10.3：

curl --header "rest_api_plugin_http_token" http://IP:8080/admin/rest_api/api?api=VERSION
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.</p>
[root@tencent airflow]# curl --header "rest_api_plugin_http_token:None" http://IP:8080/admin/rest_api/api?api=VERSION
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.</p>

**Comment by rssanders3** [comment]
Hello @wenchangming211, there is a similar issue opened to this that you can refer to and see our workaround and check for updates: https://github.com/teamclairvoyant/airflow-rest-api-plugin/issues/41

Closing the duplicate.
