### ISSUE TITLE
Compatibility with Airflow 1.10.4

### ISSUE THREAD

**Issue by joseangel-sc** [teamclairvoyant/airflow-rest-api-plugin#49]
While trying to integrate this with the newest version of airflow I am only getting a 404 (many circles) error. 

Is this related to this change? Has anybody tried to update Airflow?

**Comment by sudhakar-nallam** [comment]
@joseangel-sc Latest release v1.0.8 was tested with Airflow v1.10.4 and above. Please check and let us know if you still have the issue.

**Comment by sudhakar-nallam** [comment]
@joseangel-sc Do you have any updates on this issue?

**Comment by jainshamit** [comment]
@sudhakar-nallam Can we  send execution_date with dag trigger api?

**Comment by rssanders3** [comment]
Hello @joseangel-sc, can you confirm if this is working for you now?

**Comment by pohsiu** [comment]
@rssanders3 Hi, Looks like api refresh_all is not supported in v1.10 now ?

**Comment by prakshalj0512** [comment]
@pohsiu An issue has been opened in the Apache Airflow Github. It should be included in the next release (1.10.12). You can track the progress here: https://github.com/apache/airflow/issues/9749

In the meantime, a workaround has been implemented.
