### ISSUE TITLE
airflow POST does not work, CSRF error being produced

### ISSUE THREAD

**Issue by anton-socure** [teamclairvoyant/airflow-rest-api-plugin#56]
Hello,

I have been working with this project and have a large payload to send. POST would be the best way to send the payload, however whenever I send any POST payload, I get blocked by a CSRF check, I have gone in the code and disabled CSRF checks but I still get the error. I tried using a GET and the payload is too large (data is nearly 17000 characters) and I get a gunicorn 414 Request-URI Too Large error. I read your documentation and it mentions "Supports both http GET and POST methods." for nearly all API calls. Please update the documentation and or API to correctly reflect the expected results.

**Comment by sudhakar-nallam** [comment]
@anton-socure  Which version of Airflow you are using?

**Comment by anton-socure** [comment]
v1.10.5

**Comment by sudhakar-nallam** [comment]
Can you please try adding the following property in the webserver_config.py file in the Airflow home directory. Restart Airflow webserver and try POST method again and let us know the results.

#Flask-WTF flag for CSRF
WTF_CSRF_ENABLED = False

**Comment by anton-socure** [comment]
That worked, thank you, but the string in webserver_config.py  is CSRF_ENABLED, not WTF_CSRF_ENABLED which is why it didn't work for me

**Comment by sudhakar-nallam** [comment]
@anton-socure Thanks for the update. Yes, the default CSRF_ENABLED attribute generated by Airflow is no longer valid. We need to replace that with WTF_CSRF_ENABLED.
