### ISSUE TITLE
RBAC and JWT Auth tokens

### ISSUE THREAD

**Issue by Wu-Junjie** [teamclairvoyant/airflow-rest-api-plugin#61]
hello
I am using RBAC, but I can get the apis without JWT Auth tokens.

authenticate = True 
my airflow version is 1.10.9.

**Comment by nbenaglia** [comment]
I confirm that this plugin exposes API to everyone, it doesn't require authentication (even if auth is enabled in airflow).

**Comment by nbenaglia** [comment]
@Wu-Junjie : have you followed instructions for authentication inside [readme file](https://github.com/teamclairvoyant/airflow-rest-api-plugin#enabling-authentication )?

**Comment by Wu-Junjie** [comment]
I followed the documentation again, and it's ok now.
Maybe because I skipped a step: **Renewing the Access Token**
Thanks a lot

**Comment by nbenaglia** [comment]
You can close this issue ;)
