### ISSUE TITLE
refresh dag with dag id and refresh all dags not work

### ISSUE THREAD

**Issue by codersky** [teamclairvoyant/airflow-rest-api-plugin#63]
Here is the detail response.

{
"arguments": {
"api": "refresh_all_dags"
},
"call_time": "Mon, 30 Mar 2020 23:33:31 GMT",
"http_response_code": 500,
"output": "An error occurred while trying to Refresh all the DAGs: 'Airflow' object has no attribute 'refresh_all'",
"post_arguments": {},
"response_time": "Tue, 31 Mar 2020 07:08:24 GMT",
"status": "ERROR"
}

**Comment by codersky** [comment]
Versions
Airflow Version: 1.10.9
Rest API Plugin Version: 1.0.8

**Comment by codersky** [comment]
the refresh all function has been deleted in the version of 1.10.stable

**Comment by prakshalj0512** [comment]
An issue with Airflow has been opened and it should be resolved in the next incremental release: https://github.com/apache/airflow/issues/9749
