### ISSUE TITLE
Unable to download the plugin for 1.10.11

### ISSUE THREAD

**Issue by gowrishec** [teamclairvoyant/airflow-rest-api-plugin#70]
Hi Team,

Unable to get the airflow-rest-api-plugin for 1.10.11 version.

https://github.com/teamclairvoyant/airflow-rest-api-plugin/archive/v1.10.11-branch.zip

The  URL is giving internal server error..

Please help.

**Comment by rssanders3** [comment]
Hello @gowrishec,

The versioning of this plugin does not match the Airflow versioning. It contains its own versions. The readme lists the complete list of versions available but I'll copy them here:
```
v0.0.1
v0.0.2
v1.0.0
v1.0.1
v1.0.2
v1.0.3
v1.0.4
v1.0.5
v1.0.6
v1.0.7
v1.0.8
```
You can pull the latest from here:
https://github.com/teamclairvoyant/airflow-rest-api-plugin/archive/v1.0.8.zip

Though we are currently testing the v1.0.9 release and will have that soon with some fixes.

**Comment by rssanders3** [comment]
Release v1.0.9 is now available:
https://github.com/teamclairvoyant/airflow-rest-api-plugin/releases/tag/v1.0.9
