### ISSUE TITLE
Unpause a dag after upload

### ISSUE THREAD

**Issue by mavencode01** [teamclairvoyant/airflow-rest-api-plugin#8]
Firstly, thank you for this plugin...really becoming useful.

I noticed after uploading a `dag` via the api, it default state is `pause` and technically I'd like it to be `unpause` so the dag can run without  changing the states to `unpause`

Is there a way to set the default state to `unpause` after dag upload?

Thanks

**Comment by rssanders3** [comment]
You're welcome. I'm glad to hear that its helping.

There is actually a property in the {AIRFLOW_HOME}/airflow.cfg file that controls whether the DAG is _paused_ or _unpaused_ when it is first created:

```
[core]

# Are DAGs paused by default at creation
dags_are_paused_at_creation = True
```

You can set this to False and all the dags that you add (either manually or by the REST API Plugin) will be started in an _unpaused_ state. 

Does this help or are you suggesting an optional argument in the REST API to force the dag into a  _paused_ or _unpaused_ state after it has been uploaded?

**Comment by mavencode01** [comment]
@rssanders3 awesome, config works for our use case now

An optional argument would add more flexibly though

**Comment by rssanders3** [comment]
Ok great.

I'll see if I can add this feature in a later release of the plugin. For now I will close out the issue. 

Let me know if you have any other issue.

**Comment by rssanders3** [comment]
Changes made in commit: https://github.com/teamclairvoyant/airflow-rest-api-plugin/commit/0846a0ada85f06c1718a9da8c2535fc2b5e96d5b

**Comment by rssanders3** [comment]
Created a release with these changes: https://github.com/teamclairvoyant/airflow-rest-api-plugin/releases/tag/v1.0.2
